export const FETCH_DATA_REQUEST='FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS'
export const INCREASE_SCORE_A='INCREASE_SCORE_A'
export const INCREASE_SCORE_B='INCREASE_SCORE_B'

